### ISSUE TITLE
provide link to code.quarkus.io generation 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/extensions.quarkus.io#37] opened 2022-12-06 13:10 UTC
should cross link to code.quarkus.io to trigger of generation.

**Comment by holly-cummins** [comment] 2022-12-06 13:57
Agreed! I think this is a duplicate of #31, do you agree? It's pretty easy to do and will be well cool, so I should prioritise it.

(There's also the link to code.quarkus.io in the header, but that's less interesting than the links which are specific to the extensions... and the header may get redesigned to have less content.)

**Comment by maxandersen** [comment] 2022-12-07 01:18
Agreed it's a duplicate. Closing.

**Closed** 2022-12-07 01:18 UTC
